#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.1.2 effective-5.10 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef PUSHLY_SWIFT_H
#define PUSHLY_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import UserNotifications;
@import WebKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Pushly",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
SWIFT_CLASS("_TtC6Pushly15ActionVariation")
@interface ActionVariation : NSObject
@property (nonatomic, copy) NSString * _Nonnull title;
@end

typedef SWIFT_ENUM(NSInteger, AnimationType, open) {
  AnimationTypeCut = 0,
  AnimationTypeFade = 1,
  AnimationTypeZoomIn = 2,
  AnimationTypeZoomOut = 3,
  AnimationTypeSlideUp = 4,
  AnimationTypeSlideDown = 5,
  AnimationTypeSlideRight = 6,
  AnimationTypeSlideLeft = 7,
};

@class WKUserContentController;
@class WKScriptMessage;
SWIFT_CLASS("_TtC6Pushly14ECommWkHandler") SWIFT_AVAILABILITY(ios_app_extension,unavailable)
@interface ECommWkHandler : NSObject <WKScriptMessageHandler>
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC6Pushly31FrequencyCapWithOccurrenceLimit")
@interface FrequencyCapWithOccurrenceLimit : NSObject
@property (nonatomic, readonly) NSInteger occurrences;
@property (nonatomic, readonly) double intervalSeconds;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6Pushly18PNAppFrequencyCaps")
@interface PNAppFrequencyCaps : NSObject
@property (nonatomic, readonly, strong) FrequencyCapWithOccurrenceLimit * _Nullable prompts;
@property (nonatomic, readonly, strong) FrequencyCapWithOccurrenceLimit * _Nullable appMessages;
@end

enum PNAppMessageStyle : NSInteger;
@class PNSchedule;
SWIFT_CLASS("_TtC6Pushly12PNAppMessage")
@interface PNAppMessage : NSObject
@property (nonatomic, readonly) NSInteger id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) NSInteger priority;
@property (nonatomic, readonly) enum PNAppMessageStyle style;
@property (nonatomic, readonly, copy) NSArray<PNSchedule *> * _Nonnull schedules;
@property (nonatomic, copy) NSString * _Nullable templateHTML;
@property (nonatomic, copy) NSString * _Nullable templateUrl;
@property (nonatomic) BOOL hasDisplayed;
- (nonnull instancetype)initWithId:(NSInteger)id name:(NSString * _Nullable)name style:(enum PNAppMessageStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PNAppMessage (SWIFT_EXTENSION(Pushly))
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull conditionKeys;
- (BOOL)hasConditionKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (BOOL)meetsConditions:(NSDictionary<NSString *, NSString *> * _Nonnull)checkConditions SWIFT_WARN_UNUSED_RESULT;
@end

@class RelativeDate;
@interface PNAppMessage (SWIFT_EXTENSION(Pushly))
@property (nonatomic, readonly) BOOL isFullscreen;
@property (nonatomic, readonly) BOOL isModal;
@property (nonatomic, readonly) BOOL isBanner;
@property (nonatomic, readonly) BOOL isTopBanner;
@property (nonatomic, readonly) BOOL isBottomBanner;
@property (nonatomic, readonly) BOOL redisplayEnabled;
@property (nonatomic, readonly) double redisplayFcap;
@property (nonatomic, readonly, strong) RelativeDate * _Nonnull maxDisplayTime;
@property (nonatomic, readonly) BOOL gesturesDisabled;
@property (nonatomic, readonly) BOOL canDismissOnSlide;
@property (nonatomic, readonly) BOOL canDismissOnTapOutside;
@property (nonatomic, readonly) BOOL closeButtonVisible;
- (BOOL)isEligibleToDisplayWithSkipConditionsEvaluation:(BOOL)skipConditions skipFcapEvaluation:(BOOL)skipFcap SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BOOL hasMetSessionFrequencyCap;
@property (nonatomic, readonly) BOOL hasMetTimeInScopeCondition;
@end

typedef SWIFT_ENUM(NSInteger, PNAppMessageActionIdentifier, open) {
  PNAppMessageActionIdentifierPageLoadCompleted = 0,
  PNAppMessageActionIdentifierPrimary = 1,
  PNAppMessageActionIdentifierSecondary = 2,
  PNAppMessageActionIdentifierNone = 3,
};

SWIFT_CLASS("_TtC6Pushly18PNAppMessageConfig")
@interface PNAppMessageConfig : NSObject
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable scripts;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6Pushly29PNAppMessageDisplayConditions")
@interface PNAppMessageDisplayConditions : NSObject
@end

SWIFT_CLASS("_TtC6Pushly27PNAppMessageGroupConditions")
@interface PNAppMessageGroupConditions : NSObject
@property (nonatomic, strong) PNAppMessageDisplayConditions * _Nullable display;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable pageUrls;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable excludedPageUrls;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC6Pushly23PNAppMessageInteraction")
@interface PNAppMessageInteraction : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, PNAppMessageInteractionType, open) {
  PNAppMessageInteractionTypeOpenUrl = 0,
  PNAppMessageInteractionTypeClose = 1,
  PNAppMessageInteractionTypePromptForNotificationPermissions = 2,
  PNAppMessageInteractionTypeNone = 3,
};

SWIFT_CLASS("_TtC6Pushly28PNAppMessageInternalResponse")
@interface PNAppMessageInternalResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL("_TtP6Pushly29PNAppMessageLifecycleDelegate_")
@protocol PNAppMessageLifecycleDelegate
@optional
- (void)pushSDKWillPresentAppMessage:(PNAppMessage * _Nonnull)appMessage;
- (BOOL)pushSDKDidReceiveAppMessageInteraction:(PNAppMessageInteraction * _Nonnull)message fromAppMessage:(PNAppMessage * _Nonnull)appMessage SWIFT_WARN_UNUSED_RESULT;
- (void)pushSDKDidFailToProcessMessage:(WKScriptMessage * _Nonnull)message fromAppMessage:(PNAppMessage * _Nonnull)appMessage;
@end

typedef SWIFT_ENUM(NSInteger, PNAppMessageStyle, open) {
  PNAppMessageStyleFullscreen = 0,
  PNAppMessageStyleModal = 1,
  PNAppMessageStyleBanner = 2,
};

@class NSCoder;
SWIFT_CLASS("_TtC6Pushly16PNAppMessageView") SWIFT_AVAILABILITY(ios_app_extension,unavailable)
@interface PNAppMessageView : UIView <UIScrollViewDelegate, WKUIDelegate>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class WKWebView;
@class WKNavigation;
@class WKNavigationAction;
@class WKNavigationResponse;
SWIFT_AVAILABILITY(ios_app_extension,unavailable)
@interface PNAppMessageView (SWIFT_EXTENSION(Pushly)) <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Nonnull)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didCommitNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationResponse:(WKNavigationResponse * _Nonnull)navigationResponse decisionHandler:(void (^ _Nonnull)(WKNavigationResponsePolicy))decisionHandler;
@end

@protocol UIViewControllerTransitionCoordinator;
@class UIPanGestureRecognizer;
@class UITapGestureRecognizer;
@class NSBundle;
SWIFT_CLASS("_TtC6Pushly26PNAppMessageViewController") SWIFT_AVAILABILITY(ios_app_extension,unavailable)
@interface PNAppMessageViewController : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLayoutSubviews;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
- (void)viewWillAppear:(BOOL)animated;
- (void)panGestureRecognizerDidMove:(UIPanGestureRecognizer * _Nonnull)sender;
- (void)tapGestureRecognizerDidTap:(UITapGestureRecognizer * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

SWIFT_AVAILABILITY(ios_app_extension,unavailable)
@interface PNAppMessageViewController (SWIFT_EXTENSION(Pushly)) <WKScriptMessageHandler>
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
@end

@class UIApplication;
@class NSData;
SWIFT_CLASS("_TtC6Pushly13PNApplication") SWIFT_AVAILABILITY(ios_app_extension,unavailable)
@interface PNApplication : NSObject
- (void)pnApplication:(UIApplication * _Nonnull)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData * _Nonnull)deviceToken;
- (void)pnApplication:(UIApplication * _Nonnull)application didFailToRegisterForRemoteNotificationsWithError:(NSError * _Nonnull)error;
- (void)pnApplication:(UIApplication * _Nonnull)application didReceiveRemoteNotification:(NSDictionary * _Nonnull)userInfo fetchCompletionHandler:(void (^ _Nonnull)(UIBackgroundFetchResult))completionHandler;
- (void)pnApplication:(UIApplication * _Nonnull)application didReceiveRemoteNotification:(NSDictionary * _Nonnull)userInfo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDate;
@class PNECommConfig;
@class PNPrompt;
@class PNSessionConfig;
SWIFT_CLASS("_TtC6Pushly19PNApplicationConfig")
@interface PNApplicationConfig : NSObject
@property (nonatomic, copy) NSDate * _Nonnull fetchedAt;
@property (nonatomic, copy) NSString * _Nullable originVersion;
@property (nonatomic, readonly) uint32_t appId;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nonnull appKey;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull flags;
@property (nonatomic, readonly) UNAuthorizationOptions authorizationOptions;
@property (nonatomic, readonly, strong) PNAppFrequencyCaps * _Nullable frequencyCaps;
@property (nonatomic, readonly, strong) PNECommConfig * _Nullable ecommConfig;
@property (nonatomic, readonly, copy) NSArray<PNPrompt *> * _Nullable prompts;
@property (nonatomic, readonly, strong) PNAppMessageConfig * _Nullable appMessages;
@property (nonatomic, readonly, strong) PNSessionConfig * _Nullable sessionConfig;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSTimeZone;
@interface PNApplicationConfig (SWIFT_EXTENSION(Pushly))
@property (nonatomic, readonly) BOOL disableBadgeClearing;
@property (nonatomic, readonly) BOOL isStale;
@property (nonatomic, readonly) BOOL shouldDisplayNotificationsInForeground;
@property (nonatomic, readonly) BOOL forceDebugLogsEnabled;
@property (nonatomic, readonly) BOOL debugIdCopyDisabled;
@property (nonatomic, readonly) BOOL appMessagesEnabled;
@property (nonatomic, readonly) BOOL sdkDebugEventsEnabled;
@property (nonatomic, readonly) BOOL sdkIamCloseEventEnabled;
@property (nonatomic, readonly) BOOL subscriberSessionTrackingOnly;
@property (nonatomic, readonly, copy) NSTimeZone * _Nonnull userSessionTimezone;
@property (nonatomic, readonly) double userSessionThreshold;
@property (nonatomic, readonly, strong) FrequencyCapWithOccurrenceLimit * _Nonnull appMessageFrequencyCap;
@property (nonatomic, readonly, strong) PNPrompt * _Nullable notificationPermissionPrompt;
@end

enum PNECommItemType : NSInteger;
SWIFT_CLASS("_TtC6Pushly13PNECommConfig")
@interface PNECommConfig : NSObject
@property (nonatomic, readonly) enum PNECommItemType itemType;
@property (nonatomic, readonly, copy) NSString * _Nonnull itemTypeRawValue;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL("_TtP6Pushly11PNECommItem_")
@protocol PNECommItem
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@end

typedef SWIFT_ENUM(NSInteger, PNECommItemType, open) {
  PNECommItemTypeEvent = 0,
  PNECommItemTypeProduct = 1,
  PNECommItemTypeUnknown = 2,
};

SWIFT_CLASS("_TtC6Pushly26PNECommItemWithoutQuantity")
@interface PNECommItemWithoutQuantity : NSObject <PNECommItem>
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6Pushly24PNEventSourceApplication")
@interface PNEventSourceApplication : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, PNLiveActivityEvent, open) {
  PNLiveActivityEventEnd = 0,
};

typedef SWIFT_ENUM(NSInteger, PNLogLevel, open) {
  PNLogLevelVerbose = 0,
  PNLogLevelDebug = 1,
  PNLogLevelInfo = 2,
  PNLogLevelWarn = 3,
  PNLogLevelError = 4,
  PNLogLevelCritical = 5,
  PNLogLevelNone = 6,
};

SWIFT_CLASS("_TtC6Pushly8PNLogger")
@interface PNLogger : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) enum PNLogLevel logLevel;
- (void)verbose:(NSString * _Nonnull)message;
- (void)debug:(NSString * _Nonnull)message;
- (void)info:(NSString * _Nonnull)message;
- (void)warn:(NSString * _Nonnull)message;
- (void)error:(NSString * _Nonnull)message;
- (void)critical:(NSString * _Nonnull)message;
- (BOOL)loggingLevelEnabledFor:(enum PNLogLevel)level SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PNNotificationAction;
@class PNNotificationMeta;
@class UNNotification;
SWIFT_CLASS("_TtC6Pushly14PNNotification")
@interface PNNotification : NSObject
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable titleLocKey;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable titleLocArgs;
@property (nonatomic, copy) NSString * _Nullable subtitle;
@property (nonatomic, copy) NSString * _Nullable subtitleLocKey;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable subtitleLocArgs;
@property (nonatomic, copy) NSString * _Nullable body;
@property (nonatomic, copy) NSString * _Nullable locKey;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable locArgs;
@property (nonatomic, copy) NSString * _Nullable launchImage;
@property (nonatomic, copy) NSString * _Nullable category;
@property (nonatomic, copy) NSString * _Nullable sound;
@property (nonatomic, copy) NSString * _Nullable threadId;
@property (nonatomic) BOOL contentAvailable;
@property (nonatomic) BOOL mutableContent;
@property (nonatomic, copy) NSString * _Nullable targetContentId;
@property (nonatomic, copy) NSString * _Nullable interruptionLevel;
@property (nonatomic, copy) NSString * _Nullable filterCriteria;
@property (nonatomic, readonly) NSInteger id;
@property (nonatomic, readonly, copy) NSString * _Nonnull piid;
@property (nonatomic, readonly, copy) NSString * _Nonnull landingURL;
@property (nonatomic, copy) NSString * _Nullable imageURL;
@property (nonatomic, copy) NSString * _Nullable contentWebhookURL;
@property (nonatomic, copy) NSArray<PNNotificationAction *> * _Nonnull actions;
@property (nonatomic, copy) NSString * _Nonnull impressionType;
@property (nonatomic, strong) PNNotificationMeta * _Nullable meta;
@property (nonatomic) BOOL viaServiceExtension;
@property (nonatomic) BOOL hasRequiredKeys;
- (nonnull instancetype)initFrom:(UNNotification * _Nonnull)notification;
- (nonnull instancetype)initFromUserInfo:(NSDictionary * _Nonnull)userInfo OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PNNotification (SWIFT_EXTENSION(Pushly))
+ (BOOL)isPNNotificationPayload:(UNNotification * _Nonnull)payload SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isPNNotificationPayloadDictionary:(NSDictionary * _Nonnull)payload SWIFT_WARN_UNUSED_RESULT;
@end

enum PNNotificationActionType : NSInteger;
SWIFT_CLASS("_TtC6Pushly20PNNotificationAction")
@interface PNNotificationAction : NSObject
@property (nonatomic, readonly) uint32_t action;
@property (nonatomic, readonly) NSInteger ordinal;
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
@property (nonatomic, readonly) enum PNNotificationActionType type;
@property (nonatomic, readonly, copy) NSString * _Nullable landingURL;
@property (nonatomic, readonly) uint32_t categoryActionId;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, PNNotificationActionType, open) {
  PNNotificationActionTypeOpenURL = 0,
  PNNotificationActionTypeDismiss = 1,
};

enum PNNotificationInteractionType : NSInteger;
@class UNNotificationResponse;
SWIFT_CLASS("_TtC6Pushly25PNNotificationInteraction")
@interface PNNotificationInteraction : NSObject
@property (nonatomic, readonly) enum PNNotificationInteractionType type;
@property (nonatomic, readonly, copy) NSString * _Nonnull actionIdentifier;
@property (nonatomic, strong) PNNotification * _Nonnull notification;
- (nonnull instancetype)initFrom:(UNNotificationResponse * _Nonnull)response OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, strong) PNNotificationAction * _Nullable action;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, PNNotificationInteractionType, open) {
  PNNotificationInteractionTypeDefaultAction = 0,
  PNNotificationInteractionTypeDismissAction = 1,
  PNNotificationInteractionTypeCustomAction = 2,
};

SWIFT_PROTOCOL("_TtP6Pushly31PNNotificationLifecycleDelegate_")
@protocol PNNotificationLifecycleDelegate
@optional
- (void)pushSDKDidReceiveNotification:(PNNotification * _Nonnull)notification;
/// FALSE:   the destination was not handled and is available for processing
/// TRUE:    the client handled the event and it should not be processed
- (BOOL)pushSDKDidReceiveNotificationDestination:(NSString * _Nonnull)destination withInteraction:(PNNotificationInteraction * _Nonnull)interaction SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC6Pushly18PNNotificationMeta")
@interface PNNotificationMeta : NSObject
- (nonnull instancetype)init;
- (nonnull instancetype)initFrom:(NSDictionary<NSString *, NSObject *> * _Nullable)data OBJC_DESIGNATED_INITIALIZER;
- (BOOL)has:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (id _Nullable)getValueForKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getStringForKey:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)toDict SWIFT_WARN_UNUSED_RESULT;
@end

@class NSNumber;
@interface PNNotificationMeta (SWIFT_EXTENSION(Pushly))
- (NSNumber * _Nullable)getBoolForKey:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSNumber * _Nullable)getIntForKey:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSNumber * _Nullable)getDoubleForKey:(NSString * _Nonnull)key error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC6Pushly29PNNotificationOpenedProcessor") SWIFT_AVAILABILITY(ios_app_extension,unavailable)
@interface PNNotificationOpenedProcessor : NSObject
+ (void)processInteraction:(PNNotificationInteraction * _Nonnull)pnInteraction withDestination:(NSString * _Nonnull)destination;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UNNotificationRequest;
@class UNNotificationContent;
SWIFT_CLASS("_TtC6Pushly30PNNotificationServiceExtension")
@interface PNNotificationServiceExtension : UNNotificationServiceExtension
- (void)didReceiveNotificationRequest:(UNNotificationRequest * _Nonnull)request withContentHandler:(void (^ _Nonnull)(UNNotificationContent * _Nonnull))contentHandler;
- (void)serviceExtensionTimeWillExpire;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UNMutableNotificationContent;
SWIFT_CLASS("_TtC6Pushly37PNNotificationServiceExtensionHandler")
@interface PNNotificationServiceExtensionHandler : NSObject
+ (void)didReceiveExtensionRequest:(UNNotificationRequest * _Nonnull)request content:(UNMutableNotificationContent * _Nonnull)bestAttemptContent withContentHandler:(void (^ _Nonnull)(UNNotificationContent * _Nonnull))contentHandler;
+ (void)didRecieveExtensionTimeWillExpire:(UNMutableNotificationContent * _Nonnull)bestAttemptContent withContentHandler:(void (^ _Nonnull)(UNNotificationContent * _Nonnull))contentHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UNNotificationSettings;
SWIFT_PROTOCOL("_TtP6Pushly30PNPermissionsLifecycleDelegate_")
@protocol PNPermissionsLifecycleDelegate
@optional
- (void)pushSDKDidReceivePermissionResponse:(BOOL)granted withSettings:(UNNotificationSettings * _Nonnull)settings;
- (void)pushSDKDidReceivePermissionResponse:(BOOL)granted withSettings:(UNNotificationSettings * _Nonnull)settings withError:(NSError * _Nonnull)error;
- (void)pushSDKDidReceivePermissionStatusChange:(UNAuthorizationStatus)status withSettings:(UNNotificationSettings * _Nonnull)settings;
- (void)pushSDKDidRegisterForRemoteNotificationsWithDeviceToken:(NSString * _Nonnull)deviceToken;
- (void)pushSDKDidFailToRegisterForRemoteNotificationsWithError:(NSError * _Nonnull)error;
@end

typedef SWIFT_ENUM(NSInteger, PNPrePermissionResponse, open) {
  PNPrePermissionResponseAccepted = 0,
  PNPrePermissionResponseDismissed = 1,
};

enum PNPromptType : NSInteger;
SWIFT_CLASS("_TtC6Pushly8PNPrompt")
@interface PNPrompt : NSObject
@property (nonatomic, readonly) NSInteger id;
@property (nonatomic, readonly) enum PNPromptType type;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, PNPromptType, open) {
  PNPromptTypeNotification = 0,
  PNPromptTypeUnknown = 1,
};

enum PNSubscriberStatus : NSInteger;
SWIFT_PROTOCOL("_TtP6Pushly26PNPushSDKLifecycleDelegate_")
@protocol PNPushSDKLifecycleDelegate
@optional
- (void)pushSDKDidFinishLoading:(PNApplicationConfig * _Nonnull)configuration withNotificationSettings:(UNNotificationSettings * _Nonnull)settings;
- (void)pushSDKDidExitWithSubscriberStatus:(enum PNSubscriberStatus)status withDeletedState:(BOOL)deleted;
@end

SWIFT_CLASS("_TtC6Pushly10PNSchedule")
@interface PNSchedule : NSObject
@property (nonatomic, readonly) NSInteger id;
@property (nonatomic, copy) NSString * _Nonnull runTimezone;
@property (nonatomic, readonly, copy) NSString * _Nonnull runWindow;
@property (nonatomic, readonly, copy) NSDate * _Nonnull runStart;
@property (nonatomic, readonly, copy) NSDate * _Nullable runEnd;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6Pushly15PNSessionConfig")
@interface PNSessionConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable sessionTimezone;
@property (nonatomic, strong) RelativeDate * _Nullable sessionThreshold;
@end

typedef SWIFT_ENUM(NSInteger, PNSubscriberStatus, open) {
  PNSubscriberStatusSubscribed = 0,
  PNSubscriberStatusDismissed = 1,
  PNSubscriberStatusDenied = 2,
  PNSubscriberStatusNotDetermined = 3,
};

@class UNUserNotificationCenter;
SWIFT_CLASS("_TtC6Pushly24PNUserNotificationCenter") SWIFT_AVAILABILITY(ios_app_extension,unavailable)
@interface PNUserNotificationCenter : NSObject <UNUserNotificationCenterDelegate>
- (void)pnUserNotificationCenter:(UNUserNotificationCenter * _Nonnull)center willPresent:(UNNotification * _Nonnull)notification withCompletionHandler:(void (^ _Nonnull)(UNNotificationPresentationOptions))completionHandler;
- (void)pnUserNotificationCenter:(UNUserNotificationCenter * _Nonnull)center didReceive:(UNNotificationResponse * _Nonnull)response withCompletionHandler:(void (^ _Nonnull)(void))completionHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC6Pushly26PushNotificationsWkHandler") SWIFT_AVAILABILITY(ios_app_extension,unavailable)
@interface PushNotificationsWkHandler : NSObject <WKScriptMessageHandler>
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC6Pushly7PushSDK")
@interface PushSDK : UIResponder <UIApplicationDelegate>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_AVAILABILITY(ios,introduced=16.1)
@interface PushSDK (SWIFT_EXTENSION(Pushly))
@end

SWIFT_CLASS_NAMED("LiveActivities")
@interface PushSDKLiveActivities : NSObject
+ (void)registerWithToken:(NSString * _Nonnull)token forActivity:(NSString * _Nonnull)activityId;
+ (void)track:(enum PNLiveActivityEvent)activityEvent forActivity:(NSString * _Nonnull)activityId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_AVAILABILITY(ios_app_extension,unavailable)
@interface PushSDK (SWIFT_EXTENSION(Pushly))
@end

SWIFT_CLASS_NAMED("UserProfile")
@interface PushSDKUserProfile : NSObject
/// The current user SDK identifier
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull anonymousId;)
+ (NSString * _Nonnull)anonymousId SWIFT_WARN_UNUSED_RESULT;
/// The current APNS device token, if the user is subscribed
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable token;)
+ (NSString * _Nullable)token SWIFT_WARN_UNUSED_RESULT;
/// The current user external id, if it has been set
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable externalId;)
+ (NSString * _Nullable)externalId SWIFT_WARN_UNUSED_RESULT;
+ (void)setExternalId:(NSString * _Nullable)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) enum PNSubscriberStatus subscriberStatus;)
+ (enum PNSubscriberStatus)subscriberStatus SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isSubscribed SWIFT_DEPRECATED_MSG("Use `PushSDK.PushNotifications.isSubscribed` instead.");)
+ (BOOL)isSubscribed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isDeleted;)
+ (BOOL)isDeleted SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isEligibleToPrompt SWIFT_DEPRECATED_MSG("Use `PushSDK.PushNotifications.isEligibleToPrompt` instead.");)
+ (BOOL)isEligibleToPrompt SWIFT_WARN_UNUSED_RESULT;
/// Sends a request to remove the user from eligibility to send
+ (void)requestUserDeletion;
+ (void)revertUserDeletion SWIFT_DEPRECATED_MSG("This method will be removed in a future release.");
/// Perform single key/value update the user profile
/// eg: set(true, forKey: “is_paying_subscriber”)
+ (void)set:(id _Nonnull)value forKey:(NSString * _Nonnull)key;
/// Perform bulk key/value update the user profile
/// eg: set([“is_paying_subscriber”: true, “interests”: [“politics”, “news”]])
+ (void)set:(NSDictionary<NSString *, id> * _Nonnull)data;
/// Append values to existing array properties
/// eg: append([“sports”], forKey: “interests”)
+ (void)append:(NSArray * _Nonnull)values to:(NSString * _Nonnull)key;
/// Remove values from existing array properties
/// eg: remove([“fasion”, “news”], forKey: “interests”)
+ (void)remove:(NSArray * _Nonnull)values from:(NSString * _Nonnull)key;
+ (void)trackActivityWithName:(NSString * _Nonnull)name;
+ (void)trackActivityWithName:(NSString * _Nonnull)name withTags:(NSArray<NSString *> * _Nonnull)tags;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_AVAILABILITY(ios_app_extension,unavailable)
@interface PushSDK (SWIFT_EXTENSION(Pushly))
@end

SWIFT_CLASS_NAMED("AppMessages")
@interface PushSDKAppMessages : NSObject
/// Applies triggered condition to all applicable app messages.
/// If applied trigger completes all conditions in an app message’s scope
/// and the app message is set to auto show it will be displayed.
+ (void)triggerWithCondition:(NSString * _Nonnull)condition withValue:(NSString * _Nonnull)value;
/// Applies triggered conditions to all applicable app messages.
/// If applied triggers complete all conditions in an app message’s scope
/// and the app message is set to auto show it will be displayed.
+ (void)triggerWithConditions:(NSDictionary<NSString *, NSString *> * _Nonnull)conditions;
+ (void)_platformBridgeProcessInteraction:(PNAppMessageInteraction * _Nonnull)interaction for:(PNAppMessage * _Nonnull)appMessage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_AVAILABILITY(ios_app_extension,unavailable)
@interface PushSDK (SWIFT_EXTENSION(Pushly))
@end

SWIFT_CLASS_NAMED("PushNotifications")
@interface PushSDKPushNotifications : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isSubscribed;)
+ (BOOL)isSubscribed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isEligibleToPrompt;)
+ (BOOL)isEligibleToPrompt SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isPaused;)
+ (BOOL)isPaused SWIFT_WARN_UNUSED_RESULT;
+ (void)pause;
+ (void)resume;
+ (void)showPermissionPrompt:(void (^ _Nonnull)(BOOL, UNNotificationSettings * _Nonnull, NSError * _Nullable))completion;
+ (void)executeIfSubscribed:(void (^ _Nonnull)(void))action;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_AVAILABILITY(ios_app_extension,unavailable)
@interface PushSDK (SWIFT_EXTENSION(Pushly))
@end

SWIFT_CLASS_NAMED("EComm")
@interface PushSDKEComm : NSObject
+ (void)saveItemWithItem:(PNECommItemWithoutQuantity * _Nonnull)item;
+ (void)saveItemsWithItems:(NSArray<PNECommItemWithoutQuantity *> * _Nonnull)items;
+ (void)viewItemWithItem:(PNECommItemWithoutQuantity * _Nonnull)item;
+ (void)viewItemsWithItems:(NSArray<PNECommItemWithoutQuantity *> * _Nonnull)items;
+ (void)clearCart;
+ (void)trackPurchase;
+ (void)trackPurchaseOf:(NSArray<id <PNECommItem>> * _Nonnull)items withPurchaseId:(NSString * _Nullable)purchaseId withPriceValue:(NSString * _Nullable)priceValue;
+ (void)withECommConfig:(void (^ _Nonnull)(PNECommConfig * _Nonnull))block caller:(NSString * _Nonnull)caller;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface PushSDK (SWIFT_EXTENSION(Pushly))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum PNLogLevel logLevel;)
+ (enum PNLogLevel)logLevel SWIFT_WARN_UNUSED_RESULT;
+ (void)setLogLevel:(enum PNLogLevel)newValue;
@end

SWIFT_AVAILABILITY(ios_app_extension,unavailable)
@interface PushSDK (SWIFT_EXTENSION(Pushly))
+ (void)application:(UIApplication * _Nonnull)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData * _Nonnull)deviceToken;
+ (void)application:(UIApplication * _Nonnull)application didFailToRegisterForRemoteNotificationsWithError:(NSError * _Nonnull)error;
+ (void)application:(UIApplication * _Nonnull)application didReceiveRemoteNotification:(NSDictionary * _Nonnull)userInfo fetchCompletionHandler:(void (^ _Nonnull)(UIBackgroundFetchResult))completionHandler;
+ (void)application:(UIApplication * _Nonnull)application didReceiveRemoteNotification:(NSDictionary * _Nonnull)userInfo;
+ (void)userNotificationCenter:(UNUserNotificationCenter * _Nonnull)center willPresent:(UNNotification * _Nonnull)notification withCompletionHandler:(void (^ _Nonnull)(UNNotificationPresentationOptions))completionHandler;
+ (void)userNotificationCenter:(UNUserNotificationCenter * _Nonnull)center didReceive:(UNNotificationResponse * _Nonnull)response withCompletionHandler:(void (^ _Nonnull)(void))completionHandler;
@end

SWIFT_AVAILABILITY(ios_app_extension,unavailable)
@interface PushSDK (SWIFT_EXTENSION(Pushly)) <PNPermissionsLifecycleDelegate>
- (void)pushSDKDidReceivePermissionResponse:(BOOL)granted withSettings:(UNNotificationSettings * _Nonnull)settings;
- (void)pushSDKDidReceivePermissionResponse:(BOOL)granted withSettings:(UNNotificationSettings * _Nonnull)settings withError:(NSError * _Nonnull)error;
- (void)pushSDKDidReceivePermissionStatusChange:(UNAuthorizationStatus)status withSettings:(UNNotificationSettings * _Nonnull)settings;
- (void)pushSDKDidRegisterForRemoteNotificationsWithDeviceToken:(NSString * _Nonnull)deviceToken;
- (void)pushSDKDidFailToRegisterForRemoteNotificationsWithError:(NSError * _Nonnull)error;
@end

SWIFT_AVAILABILITY(ios_app_extension,unavailable)
@interface PushSDK (SWIFT_EXTENSION(Pushly))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull appKey;)
+ (NSString * _Nonnull)appKey SWIFT_WARN_UNUSED_RESULT;
+ (void)getConfiguration:(void (^ _Nonnull)(PNApplicationConfig * _Nullable, NSError * _Nullable))completion;
+ (void)getNotificationPermissionStatus:(void (^ _Nonnull)(BOOL, UNNotificationSettings * _Nonnull))completion;
+ (void)showNativeNotificationPermissionPrompt:(void (^ _Nonnull)(BOOL, UNNotificationSettings * _Nonnull, NSError * _Nullable))completion;
+ (void)setEventSourceApplication:(PNEventSourceApplication * _Nonnull)application;
+ (void)resetBadgeCount;
+ (void)clearNotifications;
@end

SWIFT_AVAILABILITY(ios_app_extension,unavailable)
@interface PushSDK (SWIFT_EXTENSION(Pushly))
+ (void)setConfigurationAppKey:(NSString * _Nonnull)appKey withLaunchOptions:(NSDictionary<UIApplicationLaunchOptionsKey, id> * _Nullable)launchOptions;
+ (void)setConfigurationWithLaunchOptions:(NSDictionary<UIApplicationLaunchOptionsKey, id> * _Nullable)launchOptions;
+ (void)disableMethodSwizzling;
+ (void)setSDKLifecycleDelegate:(id <PNPushSDKLifecycleDelegate> _Nonnull)delegate;
+ (void)setPermissionsLifecycleDelegate:(id <PNPermissionsLifecycleDelegate> _Nonnull)delegate;
+ (void)setNotificationLifecycleDelegate:(id <PNNotificationLifecycleDelegate> _Nonnull)delegate;
+ (void)setAppMessageLifecycleDelegate:(id <PNAppMessageLifecycleDelegate> _Nonnull)delegate;
- (void)subscriberStateEvaluationTimerDidAdvance;
@end

SWIFT_CLASS("_TtC6Pushly12RelativeDate")
@interface RelativeDate : NSObject
@property (nonatomic, readonly) double intervalSeconds;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6Pushly20UserProfileWkHandler") SWIFT_AVAILABILITY(ios_app_extension,unavailable)
@interface UserProfileWkHandler : NSObject <WKScriptMessageHandler>
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
